### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by andydataguy**
Practicing submitting PR. Found a few spelling errors.

### CODE REVIEW

**Comment by belopash** [comment]
Thank you for noticing mistakes, I don't know how I missed it.😁

**Comment by belopash** [comment]
Oh, i understood a problem, you accidentally renamed import with capital letter, and also forgot to change file name

**Comment by andydataguy** [comment]
> Thank you for noticing mistakes, I don't know how I missed it.😁

No worries man! Happens to everyone

**Comment by andydataguy** [comment]
> Oh, i understood a problem, you accidentally renamed import with capital letter, and also forgot to change file name

Ooo gotcha. Thanks!

**Pull request merged**
